#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace autd3::native_methods {

enum class SourceTag : uint8_t {
  Auto = 0,
  Addr = 1,
  Request = 2,
};

struct Timeouts {
  OptionDuration connect;
  OptionDuration read;
  OptionDuration write;
};

struct Source {
  SourceTag tag;
  const char* addr;
};

struct RemoteTwinCATOption {
  Timeouts timeouts;
  Source source;
};

extern "C" {

[[nodiscard]]
ResultLink AUTDLinkRemoteTwinCAT(const char* addr, const char* ams_net_id, RemoteTwinCATOption option);

}  // extern "C"

}  // namespace autd3::native_methods
